### PR TITLE
[#175918636] add start script

### PR DESCRIPTION
**Pull request by pasqualespica**
Add `start` script referenced into `README`

### CODE REVIEW

**Review by cloudify — CHANGES_REQUESTED** [review]
I can't make it work, parcel builds and starts but I get a 404 when I try to open the provided URL

**Comment by cloudify** [comment]
@pasqualespica always include the story ID in the PR, see [here](https://pagopa.github.io/io-docs/io-handbook/development-workflow#pull-requests)

**Comment by pasqualespica** [comment]
> @pasqualespica always include the story ID in the PR, see [here](https://pagopa.github.io/io-docs/io-handbook/development-workflow#pull-requests)

ummm, after `yarn install` && `yarn start` you'll see something like that on console :
```
(base) $ yarn start
yarn run v1.22.5
$ parcel src/*.pug
Server running at http://localhost:1234 
```

and then put your browser on http://localhost:1234/index.html?p=1234

**Comment by pasqualespica** [comment]
> @pasqualespica always include the story ID in the PR, see [here](https://pagopa.github.io/io-docs/io-handbook/development-workflow#pull-requests)

yes, you are right

**Comment by infantesimone** [comment]
Good, locally it works http://localhost:1234/index.html?p=1234

**Comment by cloudify** [comment]
Ok thanks I wasn't using the full path

**Review by cloudify — APPROVED** [review]

**Pull request merged**
